# Generated by Django 4.0.4 on 2022-05-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_pizza_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzatopping',
            name='description',
            field=models.CharField(default='Pizza description', max_length=200),
            preserve_default=False,
        ),
    ]
