# Generated by Django 4.0.4 on 2022-05-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_pizzatopping_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzatopping',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.22, max_digits=10),
            preserve_default=False,
        ),
    ]
