# Generated by Django 4.0.4 on 2022-05-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_pizzatopping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzatopping',
            name='slug',
            field=models.SlugField(default='bbq'),
            preserve_default=False,
        ),
    ]
