# Generated by Django 4.0.4 on 2022-05-07 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_pizzatopping_slug'),
        ('order', '0002_rename_product_orderitem_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='pizza.pizzatopping'),
        ),
    ]
